# Generated by Django 3.1.1 on 2020-10-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='zoom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studygroups.zoominfo'),
        ),
    ]
