# Generated by Django 3.1.1 on 2020-11-03 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('studygroups', '0002_auto_20201019_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.course'),
        ),
    ]
