# Generated by Django 3.1.1 on 2020-11-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0003_studygroup_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoominfo',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoominfo',
            name='code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
