# Generated by Django 3.1.1 on 2020-11-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0004_auto_20201106_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoominfo',
            name='group_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
