# Generated by Django 3.1.1 on 2020-09-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idNumber', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('mnemonic', models.CharField(max_length=4)),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
