# Generated by Django 3.1.1 on 2020-10-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0002_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
