# Generated by Django 3.1.1 on 2020-10-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0005_auto_20201009_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentprofile.schedule'),
        ),
    ]
