# Generated by Django 3.1.1 on 2020-10-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0006_student_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
