# Generated by Django 3.1.1 on 2020-10-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0007_auto_20201009_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='num',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
