# Generated by Django 3.1.1 on 2020-10-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0008_student_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='num',
        ),
    ]
