# Generated by Django 3.1 on 2020-10-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0010_student_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
