# Generated by Django 3.1.1 on 2020-10-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0011_studygroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyGroup',
        ),
    ]
