# Generated by Django 3.1.1 on 2020-10-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0012_delete_studygroup'),
        ('studentprofile', '0011_student_edit'),
    ]

    operations = [
    ]
