# Generated by Django 3.1 on 2020-11-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0013_merge_20201022_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phoneNumber',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
