# Generated by Django 3.1 on 2020-11-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0014_student_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.PositiveSmallIntegerField(default=5551234567),
        ),
    ]
