# Generated by Django 3.1.1 on 2020-11-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0017_auto_20201110_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groupme_id',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
