# Generated by Django 3.1.1 on 2020-11-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0019_auto_20201113_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
